# Generated by Django 5.2.1 on 2025-05-29 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcp_seq', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(blank=True, max_length=30)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('kcal', models.CharField(blank=True, max_length=10)),
                ('carb', models.CharField(blank=True, max_length=10)),
                ('protein', models.CharField(blank=True, max_length=10)),
                ('fat', models.CharField(blank=True, max_length=10)),
                ('sodium', models.CharField(blank=True, max_length=10)),
                ('hash_tag', models.CharField(blank=True, max_length=100)),
                ('main_image', models.URLField(blank=True)),
                ('detail_image', models.URLField(blank=True)),
                ('ingredients_text', models.TextField(blank=True)),
                ('tip', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('exp_date', models.DateField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='fridge.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
