# Generated by Django 5.2.1 on 2025-05-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_ingredientitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='fridge.ingredient'),
        ),
    ]
